// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type.proto

package grpc.type.proto;

/**
 * Protobuf type {@code type.ReplyType}
 */
public  final class ReplyType extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:type.ReplyType)
    ReplyTypeOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ReplyType.newBuilder() to construct.
  private ReplyType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ReplyType() {
    id_ = 0L;
    typeVarchar_ = "";
    typeChar_ = "";
    typeText_ = "";
    typeInteger_ = 0;
    typeTinyint_ = 0;
    typeSmallint_ = 0;
    typeMediumint_ = 0;
    typeBigint_ = 0L;
    typeFloat_ = 0F;
    typeDouble_ = 0D;
    typeDecimal_ = "";
    typeDate_ = "";
    typeDatetime_ = "";
    typeTime_ = "";
    typeTimestamp_ = "";
    typeBlob_ = com.google.protobuf.ByteString.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ReplyType(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            id_ = input.readInt64();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            typeVarchar_ = s;
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            typeChar_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            typeText_ = s;
            break;
          }
          case 40: {

            typeInteger_ = input.readInt32();
            break;
          }
          case 48: {

            typeTinyint_ = input.readInt32();
            break;
          }
          case 56: {

            typeSmallint_ = input.readInt32();
            break;
          }
          case 64: {

            typeMediumint_ = input.readInt32();
            break;
          }
          case 72: {

            typeBigint_ = input.readInt64();
            break;
          }
          case 85: {

            typeFloat_ = input.readFloat();
            break;
          }
          case 89: {

            typeDouble_ = input.readDouble();
            break;
          }
          case 98: {
            java.lang.String s = input.readStringRequireUtf8();

            typeDecimal_ = s;
            break;
          }
          case 106: {
            java.lang.String s = input.readStringRequireUtf8();

            typeDate_ = s;
            break;
          }
          case 114: {
            java.lang.String s = input.readStringRequireUtf8();

            typeDatetime_ = s;
            break;
          }
          case 122: {
            java.lang.String s = input.readStringRequireUtf8();

            typeTime_ = s;
            break;
          }
          case 130: {
            java.lang.String s = input.readStringRequireUtf8();

            typeTimestamp_ = s;
            break;
          }
          case 138: {

            typeBlob_ = input.readBytes();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.type.proto.TypeProto.internal_static_type_ReplyType_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.type.proto.TypeProto.internal_static_type_ReplyType_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.type.proto.ReplyType.class, grpc.type.proto.ReplyType.Builder.class);
  }

  public static final int ID_FIELD_NUMBER = 1;
  private long id_;
  /**
   * <code>int64 id = 1;</code>
   */
  public long getId() {
    return id_;
  }

  public static final int TYPE_VARCHAR_FIELD_NUMBER = 2;
  private volatile java.lang.Object typeVarchar_;
  /**
   * <code>string type_varchar = 2;</code>
   */
  public java.lang.String getTypeVarchar() {
    java.lang.Object ref = typeVarchar_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      typeVarchar_ = s;
      return s;
    }
  }
  /**
   * <code>string type_varchar = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTypeVarcharBytes() {
    java.lang.Object ref = typeVarchar_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      typeVarchar_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_CHAR_FIELD_NUMBER = 3;
  private volatile java.lang.Object typeChar_;
  /**
   * <code>string type_char = 3;</code>
   */
  public java.lang.String getTypeChar() {
    java.lang.Object ref = typeChar_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      typeChar_ = s;
      return s;
    }
  }
  /**
   * <code>string type_char = 3;</code>
   */
  public com.google.protobuf.ByteString
      getTypeCharBytes() {
    java.lang.Object ref = typeChar_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      typeChar_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_TEXT_FIELD_NUMBER = 4;
  private volatile java.lang.Object typeText_;
  /**
   * <code>string type_text = 4;</code>
   */
  public java.lang.String getTypeText() {
    java.lang.Object ref = typeText_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      typeText_ = s;
      return s;
    }
  }
  /**
   * <code>string type_text = 4;</code>
   */
  public com.google.protobuf.ByteString
      getTypeTextBytes() {
    java.lang.Object ref = typeText_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      typeText_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_INTEGER_FIELD_NUMBER = 5;
  private int typeInteger_;
  /**
   * <code>int32 type_integer = 5;</code>
   */
  public int getTypeInteger() {
    return typeInteger_;
  }

  public static final int TYPE_TINYINT_FIELD_NUMBER = 6;
  private int typeTinyint_;
  /**
   * <code>int32 type_tinyint = 6;</code>
   */
  public int getTypeTinyint() {
    return typeTinyint_;
  }

  public static final int TYPE_SMALLINT_FIELD_NUMBER = 7;
  private int typeSmallint_;
  /**
   * <code>int32 type_smallint = 7;</code>
   */
  public int getTypeSmallint() {
    return typeSmallint_;
  }

  public static final int TYPE_MEDIUMINT_FIELD_NUMBER = 8;
  private int typeMediumint_;
  /**
   * <code>int32 type_mediumint = 8;</code>
   */
  public int getTypeMediumint() {
    return typeMediumint_;
  }

  public static final int TYPE_BIGINT_FIELD_NUMBER = 9;
  private long typeBigint_;
  /**
   * <code>int64 type_bigint = 9;</code>
   */
  public long getTypeBigint() {
    return typeBigint_;
  }

  public static final int TYPE_FLOAT_FIELD_NUMBER = 10;
  private float typeFloat_;
  /**
   * <code>float type_float = 10;</code>
   */
  public float getTypeFloat() {
    return typeFloat_;
  }

  public static final int TYPE_DOUBLE_FIELD_NUMBER = 11;
  private double typeDouble_;
  /**
   * <code>double type_double = 11;</code>
   */
  public double getTypeDouble() {
    return typeDouble_;
  }

  public static final int TYPE_DECIMAL_FIELD_NUMBER = 12;
  private volatile java.lang.Object typeDecimal_;
  /**
   * <code>string type_decimal = 12;</code>
   */
  public java.lang.String getTypeDecimal() {
    java.lang.Object ref = typeDecimal_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      typeDecimal_ = s;
      return s;
    }
  }
  /**
   * <code>string type_decimal = 12;</code>
   */
  public com.google.protobuf.ByteString
      getTypeDecimalBytes() {
    java.lang.Object ref = typeDecimal_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      typeDecimal_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_DATE_FIELD_NUMBER = 13;
  private volatile java.lang.Object typeDate_;
  /**
   * <code>string type_date = 13;</code>
   */
  public java.lang.String getTypeDate() {
    java.lang.Object ref = typeDate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      typeDate_ = s;
      return s;
    }
  }
  /**
   * <code>string type_date = 13;</code>
   */
  public com.google.protobuf.ByteString
      getTypeDateBytes() {
    java.lang.Object ref = typeDate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      typeDate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_DATETIME_FIELD_NUMBER = 14;
  private volatile java.lang.Object typeDatetime_;
  /**
   * <code>string type_datetime = 14;</code>
   */
  public java.lang.String getTypeDatetime() {
    java.lang.Object ref = typeDatetime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      typeDatetime_ = s;
      return s;
    }
  }
  /**
   * <code>string type_datetime = 14;</code>
   */
  public com.google.protobuf.ByteString
      getTypeDatetimeBytes() {
    java.lang.Object ref = typeDatetime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      typeDatetime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_TIME_FIELD_NUMBER = 15;
  private volatile java.lang.Object typeTime_;
  /**
   * <code>string type_time = 15;</code>
   */
  public java.lang.String getTypeTime() {
    java.lang.Object ref = typeTime_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      typeTime_ = s;
      return s;
    }
  }
  /**
   * <code>string type_time = 15;</code>
   */
  public com.google.protobuf.ByteString
      getTypeTimeBytes() {
    java.lang.Object ref = typeTime_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      typeTime_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_TIMESTAMP_FIELD_NUMBER = 16;
  private volatile java.lang.Object typeTimestamp_;
  /**
   * <code>string type_timestamp = 16;</code>
   */
  public java.lang.String getTypeTimestamp() {
    java.lang.Object ref = typeTimestamp_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      typeTimestamp_ = s;
      return s;
    }
  }
  /**
   * <code>string type_timestamp = 16;</code>
   */
  public com.google.protobuf.ByteString
      getTypeTimestampBytes() {
    java.lang.Object ref = typeTimestamp_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      typeTimestamp_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TYPE_BLOB_FIELD_NUMBER = 17;
  private com.google.protobuf.ByteString typeBlob_;
  /**
   * <code>bytes type_blob = 17;</code>
   */
  public com.google.protobuf.ByteString getTypeBlob() {
    return typeBlob_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (id_ != 0L) {
      output.writeInt64(1, id_);
    }
    if (!getTypeVarcharBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, typeVarchar_);
    }
    if (!getTypeCharBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, typeChar_);
    }
    if (!getTypeTextBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, typeText_);
    }
    if (typeInteger_ != 0) {
      output.writeInt32(5, typeInteger_);
    }
    if (typeTinyint_ != 0) {
      output.writeInt32(6, typeTinyint_);
    }
    if (typeSmallint_ != 0) {
      output.writeInt32(7, typeSmallint_);
    }
    if (typeMediumint_ != 0) {
      output.writeInt32(8, typeMediumint_);
    }
    if (typeBigint_ != 0L) {
      output.writeInt64(9, typeBigint_);
    }
    if (typeFloat_ != 0F) {
      output.writeFloat(10, typeFloat_);
    }
    if (typeDouble_ != 0D) {
      output.writeDouble(11, typeDouble_);
    }
    if (!getTypeDecimalBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 12, typeDecimal_);
    }
    if (!getTypeDateBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 13, typeDate_);
    }
    if (!getTypeDatetimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 14, typeDatetime_);
    }
    if (!getTypeTimeBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 15, typeTime_);
    }
    if (!getTypeTimestampBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 16, typeTimestamp_);
    }
    if (!typeBlob_.isEmpty()) {
      output.writeBytes(17, typeBlob_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, id_);
    }
    if (!getTypeVarcharBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, typeVarchar_);
    }
    if (!getTypeCharBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, typeChar_);
    }
    if (!getTypeTextBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, typeText_);
    }
    if (typeInteger_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(5, typeInteger_);
    }
    if (typeTinyint_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(6, typeTinyint_);
    }
    if (typeSmallint_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(7, typeSmallint_);
    }
    if (typeMediumint_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(8, typeMediumint_);
    }
    if (typeBigint_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(9, typeBigint_);
    }
    if (typeFloat_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(10, typeFloat_);
    }
    if (typeDouble_ != 0D) {
      size += com.google.protobuf.CodedOutputStream
        .computeDoubleSize(11, typeDouble_);
    }
    if (!getTypeDecimalBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(12, typeDecimal_);
    }
    if (!getTypeDateBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(13, typeDate_);
    }
    if (!getTypeDatetimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(14, typeDatetime_);
    }
    if (!getTypeTimeBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(15, typeTime_);
    }
    if (!getTypeTimestampBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(16, typeTimestamp_);
    }
    if (!typeBlob_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(17, typeBlob_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.type.proto.ReplyType)) {
      return super.equals(obj);
    }
    grpc.type.proto.ReplyType other = (grpc.type.proto.ReplyType) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getTypeVarchar()
        .equals(other.getTypeVarchar());
    result = result && getTypeChar()
        .equals(other.getTypeChar());
    result = result && getTypeText()
        .equals(other.getTypeText());
    result = result && (getTypeInteger()
        == other.getTypeInteger());
    result = result && (getTypeTinyint()
        == other.getTypeTinyint());
    result = result && (getTypeSmallint()
        == other.getTypeSmallint());
    result = result && (getTypeMediumint()
        == other.getTypeMediumint());
    result = result && (getTypeBigint()
        == other.getTypeBigint());
    result = result && (
        java.lang.Float.floatToIntBits(getTypeFloat())
        == java.lang.Float.floatToIntBits(
            other.getTypeFloat()));
    result = result && (
        java.lang.Double.doubleToLongBits(getTypeDouble())
        == java.lang.Double.doubleToLongBits(
            other.getTypeDouble()));
    result = result && getTypeDecimal()
        .equals(other.getTypeDecimal());
    result = result && getTypeDate()
        .equals(other.getTypeDate());
    result = result && getTypeDatetime()
        .equals(other.getTypeDatetime());
    result = result && getTypeTime()
        .equals(other.getTypeTime());
    result = result && getTypeTimestamp()
        .equals(other.getTypeTimestamp());
    result = result && getTypeBlob()
        .equals(other.getTypeBlob());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getId());
    hash = (37 * hash) + TYPE_VARCHAR_FIELD_NUMBER;
    hash = (53 * hash) + getTypeVarchar().hashCode();
    hash = (37 * hash) + TYPE_CHAR_FIELD_NUMBER;
    hash = (53 * hash) + getTypeChar().hashCode();
    hash = (37 * hash) + TYPE_TEXT_FIELD_NUMBER;
    hash = (53 * hash) + getTypeText().hashCode();
    hash = (37 * hash) + TYPE_INTEGER_FIELD_NUMBER;
    hash = (53 * hash) + getTypeInteger();
    hash = (37 * hash) + TYPE_TINYINT_FIELD_NUMBER;
    hash = (53 * hash) + getTypeTinyint();
    hash = (37 * hash) + TYPE_SMALLINT_FIELD_NUMBER;
    hash = (53 * hash) + getTypeSmallint();
    hash = (37 * hash) + TYPE_MEDIUMINT_FIELD_NUMBER;
    hash = (53 * hash) + getTypeMediumint();
    hash = (37 * hash) + TYPE_BIGINT_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTypeBigint());
    hash = (37 * hash) + TYPE_FLOAT_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getTypeFloat());
    hash = (37 * hash) + TYPE_DOUBLE_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        java.lang.Double.doubleToLongBits(getTypeDouble()));
    hash = (37 * hash) + TYPE_DECIMAL_FIELD_NUMBER;
    hash = (53 * hash) + getTypeDecimal().hashCode();
    hash = (37 * hash) + TYPE_DATE_FIELD_NUMBER;
    hash = (53 * hash) + getTypeDate().hashCode();
    hash = (37 * hash) + TYPE_DATETIME_FIELD_NUMBER;
    hash = (53 * hash) + getTypeDatetime().hashCode();
    hash = (37 * hash) + TYPE_TIME_FIELD_NUMBER;
    hash = (53 * hash) + getTypeTime().hashCode();
    hash = (37 * hash) + TYPE_TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + getTypeTimestamp().hashCode();
    hash = (37 * hash) + TYPE_BLOB_FIELD_NUMBER;
    hash = (53 * hash) + getTypeBlob().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.type.proto.ReplyType parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.type.proto.ReplyType parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.type.proto.ReplyType parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.type.proto.ReplyType parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.type.proto.ReplyType parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.type.proto.ReplyType parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.type.proto.ReplyType parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.type.proto.ReplyType parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.type.proto.ReplyType parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.type.proto.ReplyType parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.type.proto.ReplyType parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.type.proto.ReplyType parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.type.proto.ReplyType prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code type.ReplyType}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:type.ReplyType)
      grpc.type.proto.ReplyTypeOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.type.proto.TypeProto.internal_static_type_ReplyType_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.type.proto.TypeProto.internal_static_type_ReplyType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.type.proto.ReplyType.class, grpc.type.proto.ReplyType.Builder.class);
    }

    // Construct using grpc.type.proto.ReplyType.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      id_ = 0L;

      typeVarchar_ = "";

      typeChar_ = "";

      typeText_ = "";

      typeInteger_ = 0;

      typeTinyint_ = 0;

      typeSmallint_ = 0;

      typeMediumint_ = 0;

      typeBigint_ = 0L;

      typeFloat_ = 0F;

      typeDouble_ = 0D;

      typeDecimal_ = "";

      typeDate_ = "";

      typeDatetime_ = "";

      typeTime_ = "";

      typeTimestamp_ = "";

      typeBlob_ = com.google.protobuf.ByteString.EMPTY;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.type.proto.TypeProto.internal_static_type_ReplyType_descriptor;
    }

    public grpc.type.proto.ReplyType getDefaultInstanceForType() {
      return grpc.type.proto.ReplyType.getDefaultInstance();
    }

    public grpc.type.proto.ReplyType build() {
      grpc.type.proto.ReplyType result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public grpc.type.proto.ReplyType buildPartial() {
      grpc.type.proto.ReplyType result = new grpc.type.proto.ReplyType(this);
      result.id_ = id_;
      result.typeVarchar_ = typeVarchar_;
      result.typeChar_ = typeChar_;
      result.typeText_ = typeText_;
      result.typeInteger_ = typeInteger_;
      result.typeTinyint_ = typeTinyint_;
      result.typeSmallint_ = typeSmallint_;
      result.typeMediumint_ = typeMediumint_;
      result.typeBigint_ = typeBigint_;
      result.typeFloat_ = typeFloat_;
      result.typeDouble_ = typeDouble_;
      result.typeDecimal_ = typeDecimal_;
      result.typeDate_ = typeDate_;
      result.typeDatetime_ = typeDatetime_;
      result.typeTime_ = typeTime_;
      result.typeTimestamp_ = typeTimestamp_;
      result.typeBlob_ = typeBlob_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.type.proto.ReplyType) {
        return mergeFrom((grpc.type.proto.ReplyType)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.type.proto.ReplyType other) {
      if (other == grpc.type.proto.ReplyType.getDefaultInstance()) return this;
      if (other.getId() != 0L) {
        setId(other.getId());
      }
      if (!other.getTypeVarchar().isEmpty()) {
        typeVarchar_ = other.typeVarchar_;
        onChanged();
      }
      if (!other.getTypeChar().isEmpty()) {
        typeChar_ = other.typeChar_;
        onChanged();
      }
      if (!other.getTypeText().isEmpty()) {
        typeText_ = other.typeText_;
        onChanged();
      }
      if (other.getTypeInteger() != 0) {
        setTypeInteger(other.getTypeInteger());
      }
      if (other.getTypeTinyint() != 0) {
        setTypeTinyint(other.getTypeTinyint());
      }
      if (other.getTypeSmallint() != 0) {
        setTypeSmallint(other.getTypeSmallint());
      }
      if (other.getTypeMediumint() != 0) {
        setTypeMediumint(other.getTypeMediumint());
      }
      if (other.getTypeBigint() != 0L) {
        setTypeBigint(other.getTypeBigint());
      }
      if (other.getTypeFloat() != 0F) {
        setTypeFloat(other.getTypeFloat());
      }
      if (other.getTypeDouble() != 0D) {
        setTypeDouble(other.getTypeDouble());
      }
      if (!other.getTypeDecimal().isEmpty()) {
        typeDecimal_ = other.typeDecimal_;
        onChanged();
      }
      if (!other.getTypeDate().isEmpty()) {
        typeDate_ = other.typeDate_;
        onChanged();
      }
      if (!other.getTypeDatetime().isEmpty()) {
        typeDatetime_ = other.typeDatetime_;
        onChanged();
      }
      if (!other.getTypeTime().isEmpty()) {
        typeTime_ = other.typeTime_;
        onChanged();
      }
      if (!other.getTypeTimestamp().isEmpty()) {
        typeTimestamp_ = other.typeTimestamp_;
        onChanged();
      }
      if (other.getTypeBlob() != com.google.protobuf.ByteString.EMPTY) {
        setTypeBlob(other.getTypeBlob());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.type.proto.ReplyType parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.type.proto.ReplyType) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long id_ ;
    /**
     * <code>int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder setId(long value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object typeVarchar_ = "";
    /**
     * <code>string type_varchar = 2;</code>
     */
    public java.lang.String getTypeVarchar() {
      java.lang.Object ref = typeVarchar_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        typeVarchar_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type_varchar = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTypeVarcharBytes() {
      java.lang.Object ref = typeVarchar_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typeVarchar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type_varchar = 2;</code>
     */
    public Builder setTypeVarchar(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      typeVarchar_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string type_varchar = 2;</code>
     */
    public Builder clearTypeVarchar() {
      
      typeVarchar_ = getDefaultInstance().getTypeVarchar();
      onChanged();
      return this;
    }
    /**
     * <code>string type_varchar = 2;</code>
     */
    public Builder setTypeVarcharBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      typeVarchar_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object typeChar_ = "";
    /**
     * <code>string type_char = 3;</code>
     */
    public java.lang.String getTypeChar() {
      java.lang.Object ref = typeChar_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        typeChar_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type_char = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTypeCharBytes() {
      java.lang.Object ref = typeChar_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typeChar_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type_char = 3;</code>
     */
    public Builder setTypeChar(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      typeChar_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string type_char = 3;</code>
     */
    public Builder clearTypeChar() {
      
      typeChar_ = getDefaultInstance().getTypeChar();
      onChanged();
      return this;
    }
    /**
     * <code>string type_char = 3;</code>
     */
    public Builder setTypeCharBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      typeChar_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object typeText_ = "";
    /**
     * <code>string type_text = 4;</code>
     */
    public java.lang.String getTypeText() {
      java.lang.Object ref = typeText_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        typeText_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type_text = 4;</code>
     */
    public com.google.protobuf.ByteString
        getTypeTextBytes() {
      java.lang.Object ref = typeText_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typeText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type_text = 4;</code>
     */
    public Builder setTypeText(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      typeText_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string type_text = 4;</code>
     */
    public Builder clearTypeText() {
      
      typeText_ = getDefaultInstance().getTypeText();
      onChanged();
      return this;
    }
    /**
     * <code>string type_text = 4;</code>
     */
    public Builder setTypeTextBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      typeText_ = value;
      onChanged();
      return this;
    }

    private int typeInteger_ ;
    /**
     * <code>int32 type_integer = 5;</code>
     */
    public int getTypeInteger() {
      return typeInteger_;
    }
    /**
     * <code>int32 type_integer = 5;</code>
     */
    public Builder setTypeInteger(int value) {
      
      typeInteger_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 type_integer = 5;</code>
     */
    public Builder clearTypeInteger() {
      
      typeInteger_ = 0;
      onChanged();
      return this;
    }

    private int typeTinyint_ ;
    /**
     * <code>int32 type_tinyint = 6;</code>
     */
    public int getTypeTinyint() {
      return typeTinyint_;
    }
    /**
     * <code>int32 type_tinyint = 6;</code>
     */
    public Builder setTypeTinyint(int value) {
      
      typeTinyint_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 type_tinyint = 6;</code>
     */
    public Builder clearTypeTinyint() {
      
      typeTinyint_ = 0;
      onChanged();
      return this;
    }

    private int typeSmallint_ ;
    /**
     * <code>int32 type_smallint = 7;</code>
     */
    public int getTypeSmallint() {
      return typeSmallint_;
    }
    /**
     * <code>int32 type_smallint = 7;</code>
     */
    public Builder setTypeSmallint(int value) {
      
      typeSmallint_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 type_smallint = 7;</code>
     */
    public Builder clearTypeSmallint() {
      
      typeSmallint_ = 0;
      onChanged();
      return this;
    }

    private int typeMediumint_ ;
    /**
     * <code>int32 type_mediumint = 8;</code>
     */
    public int getTypeMediumint() {
      return typeMediumint_;
    }
    /**
     * <code>int32 type_mediumint = 8;</code>
     */
    public Builder setTypeMediumint(int value) {
      
      typeMediumint_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 type_mediumint = 8;</code>
     */
    public Builder clearTypeMediumint() {
      
      typeMediumint_ = 0;
      onChanged();
      return this;
    }

    private long typeBigint_ ;
    /**
     * <code>int64 type_bigint = 9;</code>
     */
    public long getTypeBigint() {
      return typeBigint_;
    }
    /**
     * <code>int64 type_bigint = 9;</code>
     */
    public Builder setTypeBigint(long value) {
      
      typeBigint_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 type_bigint = 9;</code>
     */
    public Builder clearTypeBigint() {
      
      typeBigint_ = 0L;
      onChanged();
      return this;
    }

    private float typeFloat_ ;
    /**
     * <code>float type_float = 10;</code>
     */
    public float getTypeFloat() {
      return typeFloat_;
    }
    /**
     * <code>float type_float = 10;</code>
     */
    public Builder setTypeFloat(float value) {
      
      typeFloat_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>float type_float = 10;</code>
     */
    public Builder clearTypeFloat() {
      
      typeFloat_ = 0F;
      onChanged();
      return this;
    }

    private double typeDouble_ ;
    /**
     * <code>double type_double = 11;</code>
     */
    public double getTypeDouble() {
      return typeDouble_;
    }
    /**
     * <code>double type_double = 11;</code>
     */
    public Builder setTypeDouble(double value) {
      
      typeDouble_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double type_double = 11;</code>
     */
    public Builder clearTypeDouble() {
      
      typeDouble_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object typeDecimal_ = "";
    /**
     * <code>string type_decimal = 12;</code>
     */
    public java.lang.String getTypeDecimal() {
      java.lang.Object ref = typeDecimal_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        typeDecimal_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type_decimal = 12;</code>
     */
    public com.google.protobuf.ByteString
        getTypeDecimalBytes() {
      java.lang.Object ref = typeDecimal_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typeDecimal_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type_decimal = 12;</code>
     */
    public Builder setTypeDecimal(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      typeDecimal_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string type_decimal = 12;</code>
     */
    public Builder clearTypeDecimal() {
      
      typeDecimal_ = getDefaultInstance().getTypeDecimal();
      onChanged();
      return this;
    }
    /**
     * <code>string type_decimal = 12;</code>
     */
    public Builder setTypeDecimalBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      typeDecimal_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object typeDate_ = "";
    /**
     * <code>string type_date = 13;</code>
     */
    public java.lang.String getTypeDate() {
      java.lang.Object ref = typeDate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        typeDate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type_date = 13;</code>
     */
    public com.google.protobuf.ByteString
        getTypeDateBytes() {
      java.lang.Object ref = typeDate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typeDate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type_date = 13;</code>
     */
    public Builder setTypeDate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      typeDate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string type_date = 13;</code>
     */
    public Builder clearTypeDate() {
      
      typeDate_ = getDefaultInstance().getTypeDate();
      onChanged();
      return this;
    }
    /**
     * <code>string type_date = 13;</code>
     */
    public Builder setTypeDateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      typeDate_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object typeDatetime_ = "";
    /**
     * <code>string type_datetime = 14;</code>
     */
    public java.lang.String getTypeDatetime() {
      java.lang.Object ref = typeDatetime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        typeDatetime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type_datetime = 14;</code>
     */
    public com.google.protobuf.ByteString
        getTypeDatetimeBytes() {
      java.lang.Object ref = typeDatetime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typeDatetime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type_datetime = 14;</code>
     */
    public Builder setTypeDatetime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      typeDatetime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string type_datetime = 14;</code>
     */
    public Builder clearTypeDatetime() {
      
      typeDatetime_ = getDefaultInstance().getTypeDatetime();
      onChanged();
      return this;
    }
    /**
     * <code>string type_datetime = 14;</code>
     */
    public Builder setTypeDatetimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      typeDatetime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object typeTime_ = "";
    /**
     * <code>string type_time = 15;</code>
     */
    public java.lang.String getTypeTime() {
      java.lang.Object ref = typeTime_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        typeTime_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type_time = 15;</code>
     */
    public com.google.protobuf.ByteString
        getTypeTimeBytes() {
      java.lang.Object ref = typeTime_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typeTime_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type_time = 15;</code>
     */
    public Builder setTypeTime(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      typeTime_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string type_time = 15;</code>
     */
    public Builder clearTypeTime() {
      
      typeTime_ = getDefaultInstance().getTypeTime();
      onChanged();
      return this;
    }
    /**
     * <code>string type_time = 15;</code>
     */
    public Builder setTypeTimeBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      typeTime_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object typeTimestamp_ = "";
    /**
     * <code>string type_timestamp = 16;</code>
     */
    public java.lang.String getTypeTimestamp() {
      java.lang.Object ref = typeTimestamp_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        typeTimestamp_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string type_timestamp = 16;</code>
     */
    public com.google.protobuf.ByteString
        getTypeTimestampBytes() {
      java.lang.Object ref = typeTimestamp_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        typeTimestamp_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string type_timestamp = 16;</code>
     */
    public Builder setTypeTimestamp(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      typeTimestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string type_timestamp = 16;</code>
     */
    public Builder clearTypeTimestamp() {
      
      typeTimestamp_ = getDefaultInstance().getTypeTimestamp();
      onChanged();
      return this;
    }
    /**
     * <code>string type_timestamp = 16;</code>
     */
    public Builder setTypeTimestampBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      typeTimestamp_ = value;
      onChanged();
      return this;
    }

    private com.google.protobuf.ByteString typeBlob_ = com.google.protobuf.ByteString.EMPTY;
    /**
     * <code>bytes type_blob = 17;</code>
     */
    public com.google.protobuf.ByteString getTypeBlob() {
      return typeBlob_;
    }
    /**
     * <code>bytes type_blob = 17;</code>
     */
    public Builder setTypeBlob(com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      typeBlob_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>bytes type_blob = 17;</code>
     */
    public Builder clearTypeBlob() {
      
      typeBlob_ = getDefaultInstance().getTypeBlob();
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:type.ReplyType)
  }

  // @@protoc_insertion_point(class_scope:type.ReplyType)
  private static final grpc.type.proto.ReplyType DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.type.proto.ReplyType();
  }

  public static grpc.type.proto.ReplyType getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ReplyType>
      PARSER = new com.google.protobuf.AbstractParser<ReplyType>() {
    public ReplyType parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ReplyType(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ReplyType> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ReplyType> getParserForType() {
    return PARSER;
  }

  public grpc.type.proto.ReplyType getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

