// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type.proto

package grpc.type.proto;

public interface ReplyTypeWrapperOrBuilder extends
    // @@protoc_insertion_point(interface_extends:type.ReplyTypeWrapper)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.google.protobuf.Int64Value id = 1;</code>
   */
  boolean hasId();
  /**
   * <code>.google.protobuf.Int64Value id = 1;</code>
   */
  com.google.protobuf.Int64Value getId();
  /**
   * <code>.google.protobuf.Int64Value id = 1;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getIdOrBuilder();

  /**
   * <code>.google.protobuf.StringValue type_varchar = 2;</code>
   */
  boolean hasTypeVarchar();
  /**
   * <code>.google.protobuf.StringValue type_varchar = 2;</code>
   */
  com.google.protobuf.StringValue getTypeVarchar();
  /**
   * <code>.google.protobuf.StringValue type_varchar = 2;</code>
   */
  com.google.protobuf.StringValueOrBuilder getTypeVarcharOrBuilder();

  /**
   * <code>.google.protobuf.StringValue type_char = 3;</code>
   */
  boolean hasTypeChar();
  /**
   * <code>.google.protobuf.StringValue type_char = 3;</code>
   */
  com.google.protobuf.StringValue getTypeChar();
  /**
   * <code>.google.protobuf.StringValue type_char = 3;</code>
   */
  com.google.protobuf.StringValueOrBuilder getTypeCharOrBuilder();

  /**
   * <code>.google.protobuf.StringValue type_text = 4;</code>
   */
  boolean hasTypeText();
  /**
   * <code>.google.protobuf.StringValue type_text = 4;</code>
   */
  com.google.protobuf.StringValue getTypeText();
  /**
   * <code>.google.protobuf.StringValue type_text = 4;</code>
   */
  com.google.protobuf.StringValueOrBuilder getTypeTextOrBuilder();

  /**
   * <code>.google.protobuf.Int32Value type_integer = 5;</code>
   */
  boolean hasTypeInteger();
  /**
   * <code>.google.protobuf.Int32Value type_integer = 5;</code>
   */
  com.google.protobuf.Int32Value getTypeInteger();
  /**
   * <code>.google.protobuf.Int32Value type_integer = 5;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getTypeIntegerOrBuilder();

  /**
   * <code>.google.protobuf.Int32Value type_tinyint = 6;</code>
   */
  boolean hasTypeTinyint();
  /**
   * <code>.google.protobuf.Int32Value type_tinyint = 6;</code>
   */
  com.google.protobuf.Int32Value getTypeTinyint();
  /**
   * <code>.google.protobuf.Int32Value type_tinyint = 6;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getTypeTinyintOrBuilder();

  /**
   * <code>.google.protobuf.Int32Value type_smallint = 7;</code>
   */
  boolean hasTypeSmallint();
  /**
   * <code>.google.protobuf.Int32Value type_smallint = 7;</code>
   */
  com.google.protobuf.Int32Value getTypeSmallint();
  /**
   * <code>.google.protobuf.Int32Value type_smallint = 7;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getTypeSmallintOrBuilder();

  /**
   * <code>.google.protobuf.Int32Value type_mediumint = 8;</code>
   */
  boolean hasTypeMediumint();
  /**
   * <code>.google.protobuf.Int32Value type_mediumint = 8;</code>
   */
  com.google.protobuf.Int32Value getTypeMediumint();
  /**
   * <code>.google.protobuf.Int32Value type_mediumint = 8;</code>
   */
  com.google.protobuf.Int32ValueOrBuilder getTypeMediumintOrBuilder();

  /**
   * <code>.google.protobuf.Int64Value type_bigint = 9;</code>
   */
  boolean hasTypeBigint();
  /**
   * <code>.google.protobuf.Int64Value type_bigint = 9;</code>
   */
  com.google.protobuf.Int64Value getTypeBigint();
  /**
   * <code>.google.protobuf.Int64Value type_bigint = 9;</code>
   */
  com.google.protobuf.Int64ValueOrBuilder getTypeBigintOrBuilder();

  /**
   * <code>.google.protobuf.FloatValue type_float = 10;</code>
   */
  boolean hasTypeFloat();
  /**
   * <code>.google.protobuf.FloatValue type_float = 10;</code>
   */
  com.google.protobuf.FloatValue getTypeFloat();
  /**
   * <code>.google.protobuf.FloatValue type_float = 10;</code>
   */
  com.google.protobuf.FloatValueOrBuilder getTypeFloatOrBuilder();

  /**
   * <code>.google.protobuf.DoubleValue type_double = 11;</code>
   */
  boolean hasTypeDouble();
  /**
   * <code>.google.protobuf.DoubleValue type_double = 11;</code>
   */
  com.google.protobuf.DoubleValue getTypeDouble();
  /**
   * <code>.google.protobuf.DoubleValue type_double = 11;</code>
   */
  com.google.protobuf.DoubleValueOrBuilder getTypeDoubleOrBuilder();

  /**
   * <code>.google.protobuf.StringValue type_decimal = 12;</code>
   */
  boolean hasTypeDecimal();
  /**
   * <code>.google.protobuf.StringValue type_decimal = 12;</code>
   */
  com.google.protobuf.StringValue getTypeDecimal();
  /**
   * <code>.google.protobuf.StringValue type_decimal = 12;</code>
   */
  com.google.protobuf.StringValueOrBuilder getTypeDecimalOrBuilder();

  /**
   * <code>.google.protobuf.StringValue type_date = 13;</code>
   */
  boolean hasTypeDate();
  /**
   * <code>.google.protobuf.StringValue type_date = 13;</code>
   */
  com.google.protobuf.StringValue getTypeDate();
  /**
   * <code>.google.protobuf.StringValue type_date = 13;</code>
   */
  com.google.protobuf.StringValueOrBuilder getTypeDateOrBuilder();

  /**
   * <code>.google.protobuf.StringValue type_datetime = 14;</code>
   */
  boolean hasTypeDatetime();
  /**
   * <code>.google.protobuf.StringValue type_datetime = 14;</code>
   */
  com.google.protobuf.StringValue getTypeDatetime();
  /**
   * <code>.google.protobuf.StringValue type_datetime = 14;</code>
   */
  com.google.protobuf.StringValueOrBuilder getTypeDatetimeOrBuilder();

  /**
   * <code>.google.protobuf.StringValue type_time = 15;</code>
   */
  boolean hasTypeTime();
  /**
   * <code>.google.protobuf.StringValue type_time = 15;</code>
   */
  com.google.protobuf.StringValue getTypeTime();
  /**
   * <code>.google.protobuf.StringValue type_time = 15;</code>
   */
  com.google.protobuf.StringValueOrBuilder getTypeTimeOrBuilder();

  /**
   * <code>.google.protobuf.StringValue type_timestamp = 16;</code>
   */
  boolean hasTypeTimestamp();
  /**
   * <code>.google.protobuf.StringValue type_timestamp = 16;</code>
   */
  com.google.protobuf.StringValue getTypeTimestamp();
  /**
   * <code>.google.protobuf.StringValue type_timestamp = 16;</code>
   */
  com.google.protobuf.StringValueOrBuilder getTypeTimestampOrBuilder();

  /**
   * <code>.google.protobuf.BytesValue type_blob = 17;</code>
   */
  boolean hasTypeBlob();
  /**
   * <code>.google.protobuf.BytesValue type_blob = 17;</code>
   */
  com.google.protobuf.BytesValue getTypeBlob();
  /**
   * <code>.google.protobuf.BytesValue type_blob = 17;</code>
   */
  com.google.protobuf.BytesValueOrBuilder getTypeBlobOrBuilder();
}
