// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type.proto

package grpc.type.proto;

public interface ReplyTypeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:type.ReplyType)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();

  /**
   * <code>string type_varchar = 2;</code>
   */
  java.lang.String getTypeVarchar();
  /**
   * <code>string type_varchar = 2;</code>
   */
  com.google.protobuf.ByteString
      getTypeVarcharBytes();

  /**
   * <code>string type_char = 3;</code>
   */
  java.lang.String getTypeChar();
  /**
   * <code>string type_char = 3;</code>
   */
  com.google.protobuf.ByteString
      getTypeCharBytes();

  /**
   * <code>string type_text = 4;</code>
   */
  java.lang.String getTypeText();
  /**
   * <code>string type_text = 4;</code>
   */
  com.google.protobuf.ByteString
      getTypeTextBytes();

  /**
   * <code>int32 type_integer = 5;</code>
   */
  int getTypeInteger();

  /**
   * <code>int32 type_tinyint = 6;</code>
   */
  int getTypeTinyint();

  /**
   * <code>int32 type_smallint = 7;</code>
   */
  int getTypeSmallint();

  /**
   * <code>int32 type_mediumint = 8;</code>
   */
  int getTypeMediumint();

  /**
   * <code>int64 type_bigint = 9;</code>
   */
  long getTypeBigint();

  /**
   * <code>float type_float = 10;</code>
   */
  float getTypeFloat();

  /**
   * <code>double type_double = 11;</code>
   */
  double getTypeDouble();

  /**
   * <code>string type_decimal = 12;</code>
   */
  java.lang.String getTypeDecimal();
  /**
   * <code>string type_decimal = 12;</code>
   */
  com.google.protobuf.ByteString
      getTypeDecimalBytes();

  /**
   * <code>string type_date = 13;</code>
   */
  java.lang.String getTypeDate();
  /**
   * <code>string type_date = 13;</code>
   */
  com.google.protobuf.ByteString
      getTypeDateBytes();

  /**
   * <code>string type_datetime = 14;</code>
   */
  java.lang.String getTypeDatetime();
  /**
   * <code>string type_datetime = 14;</code>
   */
  com.google.protobuf.ByteString
      getTypeDatetimeBytes();

  /**
   * <code>string type_time = 15;</code>
   */
  java.lang.String getTypeTime();
  /**
   * <code>string type_time = 15;</code>
   */
  com.google.protobuf.ByteString
      getTypeTimeBytes();

  /**
   * <code>string type_timestamp = 16;</code>
   */
  java.lang.String getTypeTimestamp();
  /**
   * <code>string type_timestamp = 16;</code>
   */
  com.google.protobuf.ByteString
      getTypeTimestampBytes();

  /**
   * <code>bytes type_blob = 17;</code>
   */
  com.google.protobuf.ByteString getTypeBlob();
}
