// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: type.proto

package grpc.type.proto;

public interface RequestIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:type.RequestId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   */
  long getId();
}
